<?php

namespace Wcg\modules\njfae;

use Yii;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'Wcg\modules\njfae\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (Yii::$app instanceof \yii\console\Application) {
            $this->controllerNamespace = 'Wcg\modules\njfae\commands';
        }
    }
}
